name: Generate Diagrams

on:
  push:
    branches: [ main ]
    paths:
      - 'plantuml-diagrams/**'
      - 'generate_diagrams.sh'
      - '.github/workflows/generate-diagrams.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Install ImageMagick
      run: sudo apt-get install -y imagemagick
      
    - name: Generate diagrams
      run: |
        chmod +x ./generate_diagrams.sh
        ./generate_diagrams.sh
        
    - name: List generated files
      run: |
        ls -la custom-diagrams/diagrams/
        
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        mkdir -p custom-diagrams/diagrams
        git add custom-diagrams/diagrams/
        git add atlas-app-sequence-diagram.md evaluation-avs-sequence-diagram.md
        git status
        git commit -m "Update diagrams" || echo "No changes to commit"
        
        # Configure for GITHUB_TOKEN permissions
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git push origin main || echo "No changes to push"
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
  deploy:
    needs: generate
    runs-on: ubuntu-latest
    
    # Deploy to GitHub Pages
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: .
        clean: true